= Carlos Anselmo Mendes Junior

[%hardbreaks]
cjuniorfox@gmail.com
+55 (21) 99610-9042
Nova Friburgo, RJ - Brasil

[%hardbreaks]
Analista de Sistemas. Desenvolvedor com experiência em Java, Oracle PL/SQL, Javascript, Node JS, Angular e MongoDB.
Experiência em infraestrutura e Middleware. Versionamento de código fonte com SVN e Git. Integração contínua, Jenkins, AWS, Docker, administração Linux. 
Proeficiencia na adoção de novas tecnologias.

github: link:[github.com/cjuniorfox/]

:icons:  font

== Formação

=== UNIP EAD -- São Paulo, SP
==== Superior técnico Análise e Desenvolvimento de sistemas
2020 - 2021

=== Certificação Associate Cloud Engineer, Google Cloud -- São Paulo, SP
https://www.credential.net/fb190437-d2a7-47b8-8ae5-44b3dabf3c12

O Associate Cloud Engineer realiza o deploy de aplicações, monitora operações e gerencia soluções empresariais. Pode utilizar o Google Cloud via CLI para realização de tarefas gerais na sustentação de um ou várias soluções que se beneficiam de serviços, tanto gerenciados pelo Google quanto serviços gerenciados pelo cliente no Google Cloud. 

=== Universidade CEDERJ (UFF/UFRJ) -- Niterói, RJ
==== Superior em Ciência da Computação
2011 - 2014

=== Sesc (Microsoft Technet) -- Rio de Janeiro, RJ
==== Curso de desenvolvimento CSharp
2008

=== Colégio São Gonçalo -- São Gonçalo, RJ
==== Ensino médio profissionalizante em Processamento de Dados
2000 - 2002

== Experiência

=== GFT Tecnologies SE
==== Analista desenvolvedor Java, PL/SQL e Linux -- Barueri, SP
01/2021 - Atualidade

==== Atribuições
Desenvolvimento e sustentação dos frameworks dos sistemas B3 - Balcão.

==== Tecnologias
* Java
* Bancos de dados PL/SQL
* Middleware (Oracle Weblogic 12c e 11g)
* Serviços JSON/REST e SOAP
* Mensageria Oracle e IBM
* Bitbucket (GIT)
* Testes unitários JUnit
* Administração Solaris / Linux / Windows Server

==== Principais projetos

===== *Framework NoMe (B3/Cetip)*

Base para sistemas para Cetip/Balcão
Solução se trata de um framework multifuncional que tem como objetivo facilitar, integrar e padronizar módulos e sistemas relacionados ao Balcão.

* Oracle
* PL/SOL
* Webservices
* JSON/REST
* Banco de dados Oracle

===== *Mensageria MM (B3/Cetip)*

Sistema de apoio ao balcão para enfilerar, validar e integrar as aplicações Balcão com as empresas participantes

* Mensageira IBM MQ
* Mensageria Oracle
* Java 7 / 8
* Oracle
* PS-SQL

=== Secretaria de Estado de Fazenda (SEFAZ-RJ) -- Rio de Janeiro, RJ
==== Analista de Sistemas Java e PL/SQL
04/2013 - 01/2021

==== Atribuições
Análise e desenvolvimento de sistemas, análise de negócio, diagramação e modelagem de dados, levantamento de Requisitos.

==== Tecnologias
* Java
* JSF e Angular
* Spring Boot
* Serviços JSON/REST e SOAP
* Middleware (EAP 7.1 e Oracle Weblogic 12c)
* Banco de dados Oracle e PLSQL
* Versionamento SVN e GIT
* Integração Contínua
* Testes unitários JUnit / Jacoco
* Administração Linux

==== Principais projetos

===== *Serviço de Gestão Tributária*

Controle do Crédito Tributário Estadual. Gestão de débitos do contribuinte. Emissão de Documentos de Arrecadação do tipo GNRE. Modelo de negócio em DDD *Domain Driven Design*.
A solução disponibiliza endpoints JSON/REST para integrações com sistemas corporativos da SEFAZ e endpoint SOAP 1.1 para integração com Portal GNRE Nacional. link:[www.gnre.pe.gov.br/gnre].

* Spring Boot
* Webservice SOAP 1.1
* Integração com sistemas de importação
* JSON/REST
* Integração contínua, Testes Unitários
* UML, Modelo de dados, Diagrama de fluxo de processo BPMN
* Banco de dados Relacional Oracle
* PL/SQL
* Apache
* Weblogic 12c e JBoss EAP 7.1

===== *GCT -- Emissão e processamento de documento de arrecadação do tipo DARJ*

Sistema de processamento e emissão de arrecadação do tipo DARJ e GNRE legado. Processamento de remessas bancárias e vinculação de pagamentos. link:[www1.fazenda.rj.gov.br/projetoGCTBradesco]

* Spring Boot
* JSP
* Carga de dados e ETL em PL/SQL
* Integrações com sistemas corporativos via banco de dados
* Webservice SOAP

===== *Fisco Fácil -- Sistema de Autorregularização Fiscal*

Automatização e autorregularização fiscal do crédito tributário, facilitando a auditoria fiscal. Carga e cruzamento de malhas fiscais do contribuinte.
Aplicação com Frontend JSF e integrações com sistemas corporativos em JSON/REST.

Tecnologias

* Java EE
* Java Servlet Faces (JSF)
* Cliente e serviços JSON/REST
* Banco de dados Relacional Oracle
* Jobs Jenkins para carga e ETL de dados. SQL Loader e SQLPlus
* Integração contínua em SVN e Jobs Jenkins com testes unitários

*SINCAD -- Sistema Estadual de Cadastro de Contribuíntes*

Desenvolvimento de serviço para solução corporativa para cadastro e controle de contribuíntes estadual.

* Spring Boot
* Spring Data Rest
* Integração contínua

*Refiz Parcelamento IPVA*

Emissão de documentos de arrecadação de parcelamento IPVA renegociados por Refiz. link:[www1.fazenda.rj.gov.br/parcelamentoipva/]

* Integração com sistemas corporativos via banco de dados em PL/SQL
* Spring Boot
* Java Servlet Faces (JSF)

=== Instituto Nacional de Propriedade Industrial (INPI) -- Rio de Janeiro, RJ
==== Desenvolvedor Java e PHP
11/2012 - 03/2013

* Portal INPI
* PHP / MySQL e JQuery
* JavaEE com JSP

=== PHCFoco -- Rio de Janeiro, RJ
==== Desenvolvedor PHP
02/2011 - 12/2011

Home Office. Publicador de dados e pesquisa de análise setorial. Saúde ambiental e controle de pragas.

* PHP 5 e MySQL
* JQuery e JQueryUI
* Use do https://github.com/cjuniorfox/jfox-php-framework[jfox-php-framework] em alguns módulos do sistema

=== Editora Ciência Moderna
==== Desenvolvedor PHP e Administrador Middleware
05/2010 - 01/2011

* Content Server (Adobe® CS)
* Tomcat
* Aplicação E-commerce 
* Portal da editora http://www.lcm.com.br
Foi utilizado o framework https://github.com/cjuniorfox/jfox-php-framework[jfox-php-framework] no desenvolvimento do site e alguns módulos administrativos

_Devido ao bom relacionamento que mantenho com meus antigos empregadores, sigo responsável pela manutenção do site e do Content Server_

=== Datacorpore
==== Desenvolvedor PHP
01/2010 - 03/2010

* Desenvolvimento de aplicação PHP para métricas de rede como, medição de velocidade, ping e teste de DNS reverso.
* Desenvolvimento de painel de gerênciamento VoIP

=== Allen Informática
==== Técnico em Service Desk
03/2007 - 12/2009

Assistência a empresas voltadas para área de educação (PUC-RJ e Cultura Inglesa)

* Assistência a afiliada brasileira da gravadora Sony Music
* Suporte ao usuário de 3º e 2º nível
* Coordenador de equipe de 2º nível de service desk
* Manutenção de equopamentos especiais voltados para educação
* Administração de Windows Server 2003 (Domain e Active Directory)
* Automatização de processo de atualização de material didático

== Outras experiências

Angular 8 e MongoDB

Framework PHP (jfox-php-framework) https://github.com/cjuniorfox/jfox-php-framework com objetivo de otimizar a performace de aplicações e facilitar seu desenvolvimento.

Sites desenvolvidos com o framework:

* Editora Ciência Moderna http://www.lcm.com.br
* MCA Estudio http://www.mcaestudio.com.br

=== Códigos de Exemplo

Angular
[%hardbreaks]
https://github.com/cjuniorfox/car-manager-angular/

[%hardbreaks]
Node.JS
https://github.com/cjuniorfox/car-manager-nodejs/

[%hardbreaks]
PHP
https://github.com/cjuniorfox/jfox-php-framework

[%hardbreaks]
Linux / SH
https://github.com/cjuniorfox/archraid

